- xiaomi.vacuum.gen1/firmwarebuilder/imagebuilder.sh
avoid the  `./imagebuilder.sh: line 116: output/v11_003077.md5: No such file or directory`  error
> Fix small issue in script

- xiaomi.vacuum.gen1/firmwarebuilder/imagebuilder.sh
Using test-command on IS_MAC always returns true, since in the way it is used it only checks for non-empty strings. This returns the same value for true and false.
If this is done without the test command, the shell built-ins true and false are used. These return the expected values and make the plattform chekc work properly.
> Plattform-check always detects mac plattform instead of linux

- xiaomi.vacuum.gen1/audio_generator/audio_de.csv
- xiaomi.vacuum.gen1/audio_generator/generate_audio.py
Add an audio generation script for easy generation of new audio files for unsupported languages. Script allows to use espeak-ng or the online google text to speech.
A german language example file is provided. It might need some translation improvements, but I just run out of time.
To add a new language just create a new `audio_??.csv` file and change the parameters of the `generate_audio.py` script
> Add audio generation script

- dustcloud/server.py
In the catch blocks we are trying to print(e) without first capturing it.
flake8 testing of https://github.com/dgiese/dustcloud on Python 2.7.14
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./dustcloud/server.py:52:46: F821 undefined name 'e'
print("!!! (eee) SQL rollback : %s" % str(e))
^
./dustcloud/server.py:62:46: F821 undefined name 'e'
print("!!! (eee) SQL rollback : %s" % str(e))
^
./dustcloud/server.py:72:46: F821 undefined name 'e'
print("!!! (eee) SQL rollback : %s" % str(e))
^
./dustcloud/server.py:81:46: F821 undefined name 'e'
print("!!! (eee) SQL rollback : %s" % str(e))
^
./dustcloud/server.py:531:5: F821 undefined name 'process_data'
process_data(socket,data)
^
5     F821 undefined name 'e'
```
> except: --> except Exception as e:

- UPDATE-howto.md
The mirobo library is developed as the more general miio library. The miio library can be used in the same way (see also https://github.com/dgiese/dustcloud/issues/9). Also the mac tutorial is already using it.
> change outdated mirobo library to miio

- .travis.yml
The owner of the this repo would need to go to https://travis-ci.org/profile and flip the repository switch __on__ to enable free automated flake8 testing of each pull request.
> Add free, automated flake8 testing on all new code

- .travis.yml
By reducing the git depth for travis the build speed should be improved, since the newer commits don't contain the big firmware files.
> Reduce the travis git depth

- xiaomi.vacuum.gen1/firmwarebuilder/flasher.py
Switched to python3
Using python-miio module
Automatically discover and handshake available device
Can be used to flash old devices with known token
Automatically serving http server
Drawing progress bar while downloading firmware
Automatically exiting after downloading completed
> Automatic flasher script

- xiaomi.vacuum.gen1/mapextractor/extractor.py
Extracts maps from `robot.db` database.
* Can color maps with similar colors to those found in Mi Home app.
* Works on Windows, Linux (and most likely other systems)
* No 3rd party dependencies (except Python 3)
* Exports to Netpbm image formats (grayscale/color)
Example of extracted images:
> Add map extractor

- dustcloud/server.py
- dustcloud/www/show.php
- dustcloud/www/showlog.php
Fixed UDP mode partially (no cloud forwarding yet) and some other fixes.
You can now configure server.py slightly:
```
usage: server.py [-h] [-mode {TCP,UDP}] [-redirect <HOST>:<PORT>]
[-sport SERVER_PORT]
optional arguments:
-h, --help            show this help message and exit
-mode {TCP,UDP}, --server-mode {TCP,UDP}
-redirect <HOST>:<PORT>, --http-redirect <HOST>:<PORT>
Enable http redirection to given address for messages
that aren't based on the miio protocol. Off by
default. Example: 1.2.3.4:12345.
-sport SERVER_PORT, --server-port SERVER_PORT
Listen port for the server. Defaults to 80 for -mode
TCP and 8053 for -mode UDP
```
Also reintroduced http redirection but that is not tested at all.
> Partial UDP support

- devices/xiaomi.vacuum/firmwarebuilder/imagebuilder.sh
The imagebuilder script fails on ubuntu because the umount result is not checked and the script tries to pack the not fully written image. This PR adds a check for umount and tries it again after two seconds if it fails.
Tested on Ubuntu 17.10.
> imagebuilder: Wait for umount to succeed

- Pipfile
- Pipfile.lock
- dustcloud/server.py
- dustcloud/www/config.php.dist
- dustcloud/www/fns.php
- dustcloud/www/index.php
- dustcloud/www/show.php
- dustcloud/www/showcmdlog.php
- dustcloud/www/showlog.php
- dustcloud/www/style.css
Experimented a bit with a JSON-HTTP API that server.py exposes to be able to send commands to the device immediately with feedback. Dustcloud web interface now uses AJAX to interact with the new API.
This adds a new config entry to config.php.dist so we probably need a documentation update too.
Works pretty well for me but I'd like to have other opinions on this.
Ideally, every functionality that dustcloud web interface currently provides will be moved to the JSON API so that server.py is the only one to interact with the database. This would separate the presentation part from the data and would allow developing more apps without having to directly connect to the db.
> Send manual commands to device immediately

- .gitignore
I was annoyed that git always tried to add the generated audio files for the robot.
> Exclude generated audio files from git tracking

- devices/xiaomi.vacuum/firmwarebuilder/imagebuilder.sh
The imagebuilder.sh script was broken for mac users since the used readlink from mac os doesn't know the -f option. So each time it would fail and complain about this. I've added a check so that it will complain before it starts its work:
```
(dustcloud-xEukcPtV) bash-3.2$ sudo ./imagebuilder.sh
Running on a Mac, adjusting commands accordingly
readlink from coreutils package not found! Please install it (e.g. by brew install coreutils)
```
After you've installed coreutils (don't forget to follow the instructions about adding the package to the PATH:
```
(dustcloud-xEukcPtV) bash-3.2$ sudo ./imagebuilder.sh
Running on a Mac, adjusting commands accordingly
/Users/rudelm/git/dustcloud/devices/xiaomi.vacuum/firmwarebuilder/imagebuilder.sh
compatible readlink found!
usage: sudo …
```
> fixed readlink problems on mac

- README.md
It is not immediately clear, where to find instructions on how to root and flash your device when accessing the dustcloud repository. It would be helpful if this was stated on the "landing page".
> added reference to instructions in the wiki

- dustcloud/build_map.py
- dustcloud/server.py
- dustcloud/upload_map.sh
- dustcloud/www/show.php
- dustcloud/www/style.css
This needs a helper script on the vacuum to periodically send the runtime map
and SLAM log to the dustcloud server which in turn provides an API
to display the processed image in the dustcloud web UI.
Example for periodically sending the map to the dustcloud server:
$ watch -n5 ./upload_map.sh
This probably has still room for improvement though :-)
> Show live vaccum navigation map

- README.md
This typo is also present (& fixed) in wiki documentation.
No related, but maybe this should be listed somewhere: https://github.com/OpenMiHome/mihome-binary-protocol
> = Small typo

- devices/xiaomi.vacuum/scripts/disable_logging.sh
A script to disable logging (rsyslog and Xiaomi).
Only a POC, because not all logs (rrlog.log, miio.log and watchdog.log) are disabled.
> disable logging

- dustcloud/server.py
This will closes #122 issue as the parameters wasn't correctly transmitted to miio `Message.build` (string version instead of python objects).
> Dustcloud server deserialize parameters before sending them to miio

- devices/xiaomi.vacuum/firmwarebuilder/imagebuilder.sh
If we find ssh host keys in the current directory use them. Do not
remvoe them else the hostkeys on the robot will change and your normally
don't want that.
> imagebuilder: Do no recreate ssh host keys

- devices/xiaomi.vacuum/firmwarebuilder/imagebuilder.sh
The tar_extra_file.sh also resets log file and deletes files from log rotate, we should allow to do this clean, so just remove the command which create tarballs or gzip files.
> firmwarebuilder: Let the tar_extra_file.sh do log hygiene

- devices/xiaomi.vacuum/firmwarebuilder/unprovisioned/start_wifi.sh
The current version of the `start_wifi.sh` script for configuring WPA2-PSK did not work on my gen2 robot. I refactored the script and it now works on my robot.
I think this should be tested on gen1 robots before merging.
- added logging to file for debug purposes
- removed deprecated and obsolete calls to `ifdown` and `ifconfig`
- fixed `wpa_supplicant` call (removed explicit PID file creation and unused `-C` ctrl_interface socket parameter)
> refactored start_wifi.sh to work on gen2 robots

- devices/xiaomi.vacuum/firmwarebuilder/flasher.py
Hi,
First, thanks for dustcloud!
I want to automate my process of updating with ansible, but flasher.py serving http server according to current dir, so executor has to be in relative tree to the image file.
I'm just changing http dir to path where firmware is.
Also added checking if -f option is for sure a file.
> Ability to give absoulte path to as image.

- devices/xiaomi.vacuum/firmwarebuilder/imagebuilder.sh
I added the `--hostname=HOSTNAME` parameter on the `imagebuilder.sh` to allow a custom hostname.
If the parameter is not set nothing is getting modified and the default `roborock` is used by the system.
> Add hostname parameter to roborock imagebuilder

- devices/xiaomi.vacuum/firmwarebuilder/flasher.py
1. Fix findIP() - On my (Windows 10)PC I got an issue where because of Docker I have a number of active interfaces. Old findIP() function used to retrieve the 1st address so it failed to send ota command with the correct server IP. This method works better by "pinging" the robot itself so we can get only the relevant local IP used to reach the robot's address, which makes it the correct address.
2. Add an option to manually override this local IP address. Useful when running inside docker, see #110
> Fix findIP() issue when having multiple active network interfaces

- devices/xiaomi.vacuum/firmwarebuilder/imagebuilder.sh
The untar of the soundfile failed with the previous tar command.
Tested with Ubuntu and macOS
> Fix tar command for extracting soundfile
