- xiaomi.vacuum.gen1/firmwarebuilder/imagebuilder.sh
I fixed an error in the firmware build script and cleaned up the generated files. Please review if you like the commits or tell me what to change.
BTW thank you for improving my vacuum robot :+1:
> Clean up firmware generation

- xiaomi.vacuum.gen1/firmwarebuilder/imagebuilder.sh
Use commandline arguments
Optional disabling xiaomi servers
Move default values to variables
IS_MAC changes because of https://stackoverflow.com/questions/2953646/how-to-declare-and-use-boolean-variables-in-shell-script/21210966#21210966
Identation of main code block is decreased for readability
darwin and linux "disable SSH firewall rule" part is unified
> Bash imagebuilder script improvements

- xiaomi.vacuum.gen1/miio_client_os/.gitignore
- xiaomi.vacuum.gen1/miio_client_os/CMakeLists.txt
- xiaomi.vacuum.gen1/miio_client_os/Readme.md
- xiaomi.vacuum.gen1/miio_client_os/lib/cJSON/LICENSE
- xiaomi.vacuum.gen1/miio_client_os/lib/cJSON/cJSON.c
- xiaomi.vacuum.gen1/miio_client_os/lib/cJSON/cJSON.h
- xiaomi.vacuum.gen1/miio_client_os/main.c
Here an initial version of the `miio_client_os`. The client is still in a pretty rough shape.
> add initial version of miio_client_os

- dustcloud/www/show.php
Added closing form tab before starting a new form
> Fixed form-tag for sending commands to the robot

- .gitignore
- Pipfile
- Pipfile.lock
- dustcloud/server.py
- dustcloud/www/showlog.php
This PR is more or less a work in progress that I want to use to discuss some things in the dustcloud server implementation.
Some minor fixes are included:
- Fix Message.parse() for latest python.miio package
- Completely drain all remaining data in the socket when encountering an unkown message (I sometimes receive an Unknown message: b'{"method": "local.status", "params": "cloud_connected"}', not sure where that comes from?)
- Launch both TCP and UDP servers in parallel
- Pretty print json data in dustcloud web page recv log
Fixes #26
> dustcloud fixes and refactoring

- devices/xiaomi.vacuum.gen1/mapextractor/extractor.py
> Path extraction by Balthasar Reuter

- dustcloud/server.py
> fix my_cloudserver_ip typo

- dustcloud/server.py
- dustcloud/www/show.php
to avoid the python package dependencies on bottle and pillow for minimal installs.
ref #100
> Make command server and live cleaning map optional

- dustcloud/server.py
swap forward_to_cloud and full_cloud_forward
> fix log output

- dustcloud/www/scripts.js
correct url from root to current directory for installations in non www root directorys
> correct api.php url

- devices/xiaomi.vacuum.gen1/CN_to_EU_script/CN_to_EU.sh
- devices/xiaomi.vacuum.gen1/CN_to_EU_script/README.md
I add files to be able to convert a vacuum gen1 CN to model EU.
> Added CN to EU script for xiaomi.vacuum.gen1

- dummycloud/README.md
Minor cleanup of the formatting of the README.md file.
> Cleanup of formatting of README.md

- dustcloud/www/show.php
- dustcloud/www/showcmdlog.php
- dustcloud/www/showlog.php
Use `real_escape_string` to escape parameters.
> escape sql query parameters

- devices/xiaomi.vacuum/firmwarebuilder/imagebuilder.sh
This adds an option --dummycloud to integrate dummycloud already in the patch image.
> imagebuilder: Add support for installing dummycloud

- devices/xiaomi.vacuum/firmwarebuilder/imagebuilder.sh
> fixes #165: fixed issue with SSID containing spaces in imagebuilder.sh

- devices/xiaomi.vacuum/firmwarebuilder/imagebuilder.sh
Change the script to provide path where dummycloud can be found.
> Fix dummycloud installation

- devices/xiaomi.vacuum/firmwarebuilder/imagebuilder.sh
- devices/xiaomi.vacuum/firmwarebuilder/unprovisioned/rc.local
Hi,
here are several improvements to the imagebuilder script.
> Some improvements to the imagebuilder script

- devices/xiaomi.vacuum/firmwarebuilder/imagebuilder.sh
Signed-off-by: Andreas Schneider <asn@cryptomilk.org>
> imagebuilder: Fix tar'ing the disk image file

- docker/Dockerfile_appserver
- docker/Dockerfile_webserver
- docker/README.md
- docker/docker-compose.yml
- docker/dustcloud.conf
- docker/programs.conf
- docker/supervisord.conf
Running dustcloud web with docker compose
> Build dustcloud web with docker

- devices/xiaomi.vacuum/firmwarebuilder/imagebuilder.sh
- dummycloud/doc/etc_rc.local-snippet.txt
The patches is known to work with more images and also with Gen1.
https://github.com/JohnRev/rrlogd-patcher
> imagebulider: Use the rrlogd patcher which is more reliable

- devices/xiaomi.vacuum/firmwarebuilder/imagebuilder.sh
Fix using relative path with --rrlogd-patcher=../patcher.py
> Fix using relative path with --rrlogd-patcher=../patcher.py

- .gitignore
- devices/xiaomi.vacuum/audio_generator/generate_audio.py
- dustcloud/mapserver.py
Just reading through the code and made some small PEP8 changes.   I noticed a python file was included in the .gitignore and it probably shouldn't be.  
This is super neat stuff.  Thanks for all your hard work!
> PEP8 and some string formatting changes

- devices/xiaomi.vacuum/firmwarebuilder/imagebuilder.sh
* Fix help messages
* Fix permissons
* Make soundfile optional
> Some fixes for imagebuilder

- devices/xiaomi.vacuum/firmwarebuilder/imagebuilder.sh
This changes the script to work with the latest Valetudo features.
@Hypfer will do a release once this is merged.
> imagebuilder: Adapt script to support latest Valetudo features

- devices/xiaomi.vacuum/firmwarebuilder/imagebuilder.sh
Several cosmetic changes and typos.
> Cosmetic fixes

- devices/xiaomi.vacuum/audio_generator/language/audio_pl.csv
They were a little outdated, my robot was still using original messages for e.g. zone cleanup, so I updated them, also used more friendly or natural sounding phrasing for some.
> Bring Polish translation up to date

- devices/xiaomi.vacuum/firmwarebuilder/imagebuilder.sh
Rationale is given in each commit message. I hope you find these changes useful.
> Some enhancements for imagebuilder.sh

- devices/xiaomi.vacuum/firmwarebuilder/imagebuilder.sh
See https://github.com/zvldz/vacuum/blob/master/custom-script/custom_off_logs.sh#L60
Might fix factory resets
> Added disabling of coredumps from zvldz/vacuum

- devices/xiaomi.vacuum/audio_generator/Readme.md
Update installation process for actual folder structure.
> Update installation for actual folder structure
